app-id: "cli_xxx"
app-secret: "xxx"
urls:
  - "https://xxx.feishu.cn/wiki/xxx"
dir: "/xxx/docs"
list-only: false
quit-automatically: false
file:
  extensions:
    docx: "docx" # docx 或 pdf
    doc: "docx"  # docx 或 pdf